### ISSUE TITLE
1.1.0 regressed by adding a stroke around child widgets

### ISSUE THREAD

**Issue by RyanRamchandar** [hnvn/flutter_shimmer#20]
The latest update seems to be adding a stroke around widgets now. This wasn't present before this version.

Perhaps this was introduced with the recent change to ShaderMaskLayer https://github.com/hnvn/flutter_shimmer/commit/21cc87b6b852e4f985067b038552bf88c58c1b52

Usage:
```dart
    return Container(
      child: Shimmer.fromColors(
        baseColor: baseColor,
        highlightColor: highlightColor,
        child: Wrap(
          spacing: 6,
          runSpacing: 6,
          children: <Widget>[
           //...
          ],
        ),
      ),
    );
```

![09D2BB59-A6D1-421D-B018-94177BC74126](https://user-images.githubusercontent.com/3187342/75635333-d69f8c80-5bda-11ea-9bbf-62a8dc1416ec.PNG)

**Comment by RyanRamchandar** [comment]
Here is version 1.0.1:

![image](https://user-images.githubusercontent.com/3187342/75635522-74478b80-5bdc-11ea-84a8-d6e455eb9686.png)

**Comment by RyanRamchandar** [comment]
Any ideas @hnvn?

**Comment by hnvn** [comment]
I try to modify the example project to reproduce it but it doesn't occurs:
<p>
<img src="https://media.giphy.com/media/Rl6EdukqmZVRGHHJ4S/giphy.gif"/>
</p>

You may as well modify your Widgets

**Comment by hnvn** [comment]
Have you figured out your issue yet?

**Comment by RyanRamchandar** [comment]
I wasn't able to reproduce this with the example code. I'll try to isolate the issue in my app and reopen an issue if needed.
