### ISSUE TITLE
Images in the background

### ISSUE THREAD

**Issue by eikebartels** [hnvn/flutter_shimmer#3]
It would be great to be able to put a colored image as a child.

**Comment by hnvn** [comment]
It is possible, you can see it in gif images in README file, take a look at 'slide to open' effect, it has an image background.

**Comment by eikebartels** [comment]
I have this image: 

![image](https://user-images.githubusercontent.com/767979/51170156-0217c880-18ae-11e9-9033-4f1892c28db2.png)

but when I add the `Shimmer` it becomes 

<img width="222" alt="image" src="https://user-images.githubusercontent.com/767979/51170263-4d31db80-18ae-11e9-9a2d-a993fd2d8c8a.png">

I would like to use the coloured image and add a transparent to white shimmer. Any idea?

**Comment by eikebartels** [comment]
great thank that works!
