### ISSUE TITLE
[Feature Request] Shimmer Direction at ANY angle

### ISSUE THREAD

**Issue by RyanRamchandar** [hnvn/flutter_shimmer#35]
Add support for shimmer direction at any angle. Shimmer currently supports the following four directions:

[shimmer.dart](https://github.com/hnvn/flutter_shimmer/blob/master/lib/shimmer.dart#L21)
```dart
///
/// An enum defines all supported directions of shimmer effect
///
/// * [ShimmerDirection.ltr] left to right direction
/// * [ShimmerDirection.rtl] right to left direction
/// * [ShimmerDirection.ttb] top to bottom direction
/// * [ShimmerDirection.btt] bottom to top direction
///
enum ShimmerDirection { ltr, rtl, ttb, btt }
```

**Proposal:**
Change `Shimmer` `direction` to accept a double which represents degrees (or radians).
Static constants can be used for the existing directions of `ltr, rtl, ttb, btt` for minimal changes to existing clients.

**Comment by hnvn** [comment]
You can use `gradient` parameter of `Shimmer` constructor to customize your gradient angle.
