### ISSUE TITLE
Can't add multiple widgets from different parents without adding the parents to the shimmer

### ISSUE THREAD

**Issue by erickdaros** [hnvn/flutter_shimmer#4]
When using a list we do not have this issue, but when working with a page without pattern we can not add to the same shimmer the skeleton inside different parents (in my case these parents are some cards) without adding the parents to the shimmer, what i am doing is adding multiple shimmers as we can see above but it is looking not clean since we have multiple animations instead of one

![Screenshot_20190509-094650](https://user-images.githubusercontent.com/43859767/57455140-da73b400-7240-11e9-9691-aa0408b1da8a.jpg)

When i try to use only one shimmer to all the skeleton it does add the parent cards too:

![Screenshot_20190509-100807](https://user-images.githubusercontent.com/43859767/57455955-bf09a880-7242-11e9-8165-60525b514bad.jpg)

**Comment by vitorbg2** [comment]
I have the same problem friend, if you solved it help me

**Comment by ManuLpz4** [comment]
Although I don't have to deal with that problem in my app, I think it's a good feature :)

**Comment by hnvn** [comment]
Please try it on the new v1.1.0, let me know if the issue still occurs

**Comment by hnvn** [comment]
I am going to close this issue if there's no support needed
