### ISSUE TITLE
Shimmer issue

### ISSUE THREAD

**Issue by savitore** [hnvn/flutter_shimmer#67]
Shimmer.fromColors() does not work in the latest Flutter sdk. I don't know why is this happening.

**Comment by mateusfccp** [comment]
This package is practically dead. Do you have a log of what error happens? It may be useful for the ones who are using the latest version of Flutter.

**Comment by hnvn** [comment]
Hell guys, I am using the package with Flutter v3.7.10, it works normally , is it the last Flutter SDK?

**Comment by savitore** [comment]
my bad, I am using flutter v3.7.0. In this version, Shimmer.fromColors is not in the package shimmer : ^2.0.0 but in the package shimmer : ^1.1.2, it is there.
