### ISSUE TITLE
Problem with shimmer and new flutter verision

### ISSUE THREAD

**Issue by tahamalas7** [hnvn/flutter_shimmer#9]
My flutter version is  Flutter (Channel stable, v1.7.8) and the shimmer version is 1.0.0

The problem occurred when updated flutter to the newer version.

It worked perfectly before, and I didn't change anything in my code. anyone know why this problem is occurring?

![Simulator Screen Shot - iPhone 6 - 2019-09-01 at 22 24 37](https://user-images.githubusercontent.com/54778746/64081282-66857c00-cd07-11e9-88bb-e03c42d5b284.png)

![Simulator Screen Shot - iPhone 6 - 2019-09-01 at 22 24 41](https://user-images.githubusercontent.com/54778746/64081284-671e1280-cd07-11e9-8a36-8c5226535310.png)

**Comment by hnvn** [comment]
Have you tried the example project yet?

**Comment by tahamalas7** [comment]
I just tried it and it works perfectly!.. I don't know what is the problem it was working but now not working.

The weird thing is this problem occurred in two of previous apps that I've built!

Here is the code for the second picture that I posted earlier can you please take look at it and see if there is any problem with it?.

```
ListTile(
        leading: Shimmer.fromColors(
          child: Container(
            width: 90,
            height: 90,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.white, width: 3),
              color: Colors.white,
              shape: BoxShape.circle,
            ),
          ),
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
        ),
        title: Shimmer.fromColors(
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
          child: Card(
            elevation: 0,
            child: Container(
              width: 50,
              height: 20,
            ),
          ),
        ),
        subtitle: Shimmer.fromColors(
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
          child: Card(
            elevation: 0,
            child: Container(
              height: 10,
              width: 30,
            ),
          ),
        ),
      )
```

**Comment by tahamalas7** [comment]
This is a picture of previous build I have of my app that works like charm, but I'm 100% sure that I didn't change anything in my code.


![Screen Shot 2019-09-02 at 3 08 16 PM](https://user-images.githubusercontent.com/54778746/64113638-85c9eb00-cd93-11e9-9585-a06290c2cc03.png)

**Comment by hnvn** [comment]
Give your `Container` explicit colors, either an opaque color or a transparent color.

**Comment by hnvn** [comment]
Have you resolved your problem yet? I am going to close this issue.

**Comment by tahamalas7** [comment]
> Have you resolved your problem yet? I am going to close this issue.

Unfortunately it did not.

That's the code after I added color to my containers.

Is there anything wrong with it?

```
ListTile(
        leading: Shimmer.fromColors(
          child: Container(
            width: 90,
            height: 90,
            decoration: BoxDecoration(
              border: Border.all(color: Colors.white, width: 3),
              color: Colors.white,
              shape: BoxShape.circle,
            ),
          ),
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
        ),
        title: Shimmer.fromColors(
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
          child: Card(
            color: Colors.transparent,
            elevation: 0,
            child: Container(
              color: Colors.transparent,
              width: 50,
              height: 20,
            ),
          ),
        ),
        subtitle: Shimmer.fromColors(
          highlightColor: Colors.white24,
          baseColor: Colors.white12,
          child: Card(
            color: Colors.transparent,
            elevation: 0,
            child: Container(
              color: Colors.transparent,
              height: 10,
              width: 30,
            ),
          ),
        ),
      )
```

**Comment by z234009184** [comment]
I had the same problem~ 


`SizedBox(
            width: 200,
            height: 200,
            child: Shimmer.fromColors(
                baseColor: Colors.black12,
                highlightColor: Colors.white,
                loop: 3,
                direction: ShimmerDirection.ttb,
                child: Container(child: Image.asset('images/kongche.png'),)
            ),
          )`

**Comment by tahamalas7** [comment]
> I had the same problem~
> 
> `SizedBox( width: 200, height: 200, child: Shimmer.fromColors( baseColor: Colors.black12, highlightColor: Colors.white, loop: 3, direction: ShimmerDirection.ttb, child: Container(child: Image.asset('images/kongche.png'),) ), )`

Did you figure out a way to solve it?

**Comment by tahamalas7** [comment]
Did anyone find out a solution to solve it?

**Comment by hnvn** [comment]
Don't use `ListTile` widget with `Shimmer`, it is made of many complex widgets (`InkWell`, `SafeArea`). I recommend you just use basic and simple widgets such as `Container` with `Shimmer` to avoid the side effect.
